[package]
name = "fault-injection-protection-arm"
version = "0.1.0"
edition = "2021"
authors = ["Brian Mak"]
categories = ["embedded", "no-std"]
license = "MIT"

[dependencies]
cortex-m = "0.7.7"
rand_core = "0.6.4"